# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chrome_pb2 as chrome__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ChromeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.session_changed = channel.unary_unary(
                '/trackd.Chrome/session_changed',
                request_serializer=chrome__pb2.SessionChangedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ChromeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def session_changed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChromeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'session_changed': grpc.unary_unary_rpc_method_handler(
                    servicer.session_changed,
                    request_deserializer=chrome__pb2.SessionChangedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trackd.Chrome', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chrome(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def session_changed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trackd.Chrome/session_changed',
            chrome__pb2.SessionChangedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
