# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chrome.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63hrome.proto\x12\x06trackd\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x15SessionChangedRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\"G\n\x1cSetSessionForWindowIdRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\x12\x11\n\twindow_id\x18\x02 \x01(\x03\"+\n\x16SetActiveWindowRequest\x12\x11\n\twindow_id\x18\x03 \x01(\x03\x32\xfa\x01\n\x06\x43hrome\x12H\n\x0fsession_changed\x12\x1d.trackd.SessionChangedRequest\x1a\x16.google.protobuf.Empty\x12Y\n\x19set_session_for_window_id\x12$.trackd.SetSessionForWindowIdRequest\x1a\x16.google.protobuf.Empty\x12K\n\x11set_active_window\x12\x1e.trackd.SetActiveWindowRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chrome_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SESSIONCHANGEDREQUEST']._serialized_start=53
  _globals['_SESSIONCHANGEDREQUEST']._serialized_end=98
  _globals['_SETSESSIONFORWINDOWIDREQUEST']._serialized_start=100
  _globals['_SETSESSIONFORWINDOWIDREQUEST']._serialized_end=171
  _globals['_SETACTIVEWINDOWREQUEST']._serialized_start=173
  _globals['_SETACTIVEWINDOWREQUEST']._serialized_end=216
  _globals['_CHROME']._serialized_start=219
  _globals['_CHROME']._serialized_end=469
# @@protoc_insertion_point(module_scope)
