# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chrome.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chrome.proto',
  package='trackd',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63hrome.proto\x12\x06trackd\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x15SessionChangedRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t2R\n\x06\x43hrome\x12H\n\x0fsession_changed\x12\x1d.trackd.SessionChangedRequest\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SESSIONCHANGEDREQUEST = _descriptor.Descriptor(
  name='SessionChangedRequest',
  full_name='trackd.SessionChangedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_name', full_name='trackd.SessionChangedRequest.session_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['SessionChangedRequest'] = _SESSIONCHANGEDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionChangedRequest = _reflection.GeneratedProtocolMessageType('SessionChangedRequest', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONCHANGEDREQUEST,
  '__module__' : 'chrome_pb2'
  # @@protoc_insertion_point(class_scope:trackd.SessionChangedRequest)
  })
_sym_db.RegisterMessage(SessionChangedRequest)



_CHROME = _descriptor.ServiceDescriptor(
  name='Chrome',
  full_name='trackd.Chrome',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='session_changed',
    full_name='trackd.Chrome.session_changed',
    index=0,
    containing_service=None,
    input_type=_SESSIONCHANGEDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHROME)

DESCRIPTOR.services_by_name['Chrome'] = _CHROME

# @@protoc_insertion_point(module_scope)
