# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tmux.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntmux.proto\x12\x06trackd\x1a\x1bgoogle/protobuf/empty.proto\"Z\n\x1cSetClientForXWindowIdRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x13\n\x0bx_window_id\x18\x03 \x01(\x03\"5\n\x1e\x43learClientForXWindowIdRequest\x12\x13\n\x0bx_window_id\x18\x01 \x01(\x03\"n\n\x1b\x43lientSessionChangedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x12\n\nserver_pid\x18\x03 \x01(\x03\x12\x14\n\x0csession_name\x18\x04 \x01(\t\">\n\x15\x43lientDetachedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\"l\n\x15SessionRenamedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x12\n\nserver_pid\x18\x03 \x01(\x03\x12\x18\n\x10new_session_name\x18\x04 \x01(\t\"R\n\x14SessionClosedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x12\n\nserver_pid\x18\x02 \x01(\x03\x12\x14\n\x0csession_name\x18\x03 \x01(\t2\xf5\x03\n\x04Tmux\x12Z\n\x1aset_client_for_x_window_id\x12$.trackd.SetClientForXWindowIdRequest\x1a\x16.google.protobuf.Empty\x12^\n\x1c\x63lear_client_for_x_window_id\x12&.trackd.ClearClientForXWindowIdRequest\x1a\x16.google.protobuf.Empty\x12U\n\x16\x63lient_session_changed\x12#.trackd.ClientSessionChangedRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0f\x63lient_detached\x12\x1d.trackd.ClientDetachedRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0fsession_renamed\x12\x1d.trackd.SessionRenamedRequest\x1a\x16.google.protobuf.Empty\x12\x46\n\x0esession_closed\x12\x1c.trackd.SessionClosedRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tmux_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETCLIENTFORXWINDOWIDREQUEST']._serialized_start=51
  _globals['_SETCLIENTFORXWINDOWIDREQUEST']._serialized_end=141
  _globals['_CLEARCLIENTFORXWINDOWIDREQUEST']._serialized_start=143
  _globals['_CLEARCLIENTFORXWINDOWIDREQUEST']._serialized_end=196
  _globals['_CLIENTSESSIONCHANGEDREQUEST']._serialized_start=198
  _globals['_CLIENTSESSIONCHANGEDREQUEST']._serialized_end=308
  _globals['_CLIENTDETACHEDREQUEST']._serialized_start=310
  _globals['_CLIENTDETACHEDREQUEST']._serialized_end=372
  _globals['_SESSIONRENAMEDREQUEST']._serialized_start=374
  _globals['_SESSIONRENAMEDREQUEST']._serialized_end=482
  _globals['_SESSIONCLOSEDREQUEST']._serialized_start=484
  _globals['_SESSIONCLOSEDREQUEST']._serialized_end=566
  _globals['_TMUX']._serialized_start=569
  _globals['_TMUX']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
