# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tmux.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tmux.proto',
  package='trackd',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntmux.proto\x12\x06trackd\x1a\x1bgoogle/protobuf/empty.proto\"Z\n\x1cSetClientForXWindowIdRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x13\n\x0bx_window_id\x18\x03 \x01(\x03\"5\n\x1e\x43learClientForXWindowIdRequest\x12\x13\n\x0bx_window_id\x18\x01 \x01(\x03\"n\n\x1b\x43lientSessionChangedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x12\n\nserver_pid\x18\x03 \x01(\x03\x12\x14\n\x0csession_name\x18\x04 \x01(\t\">\n\x15\x43lientDetachedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\"l\n\x15SessionRenamedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x12\n\nserver_pid\x18\x03 \x01(\x03\x12\x18\n\x10new_session_name\x18\x04 \x01(\t\"R\n\x14SessionClosedRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x12\n\nserver_pid\x18\x02 \x01(\x03\x12\x14\n\x0csession_name\x18\x03 \x01(\t2\xf5\x03\n\x04Tmux\x12Z\n\x1aset_client_for_x_window_id\x12$.trackd.SetClientForXWindowIdRequest\x1a\x16.google.protobuf.Empty\x12^\n\x1c\x63lear_client_for_x_window_id\x12&.trackd.ClearClientForXWindowIdRequest\x1a\x16.google.protobuf.Empty\x12U\n\x16\x63lient_session_changed\x12#.trackd.ClientSessionChangedRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0f\x63lient_detached\x12\x1d.trackd.ClientDetachedRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0fsession_renamed\x12\x1d.trackd.SessionRenamedRequest\x1a\x16.google.protobuf.Empty\x12\x46\n\x0esession_closed\x12\x1c.trackd.SessionClosedRequest\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SETCLIENTFORXWINDOWIDREQUEST = _descriptor.Descriptor(
  name='SetClientForXWindowIdRequest',
  full_name='trackd.SetClientForXWindowIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='trackd.SetClientForXWindowIdRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_name', full_name='trackd.SetClientForXWindowIdRequest.client_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_window_id', full_name='trackd.SetClientForXWindowIdRequest.x_window_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=141,
)


_CLEARCLIENTFORXWINDOWIDREQUEST = _descriptor.Descriptor(
  name='ClearClientForXWindowIdRequest',
  full_name='trackd.ClearClientForXWindowIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_window_id', full_name='trackd.ClearClientForXWindowIdRequest.x_window_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=196,
)


_CLIENTSESSIONCHANGEDREQUEST = _descriptor.Descriptor(
  name='ClientSessionChangedRequest',
  full_name='trackd.ClientSessionChangedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='trackd.ClientSessionChangedRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_name', full_name='trackd.ClientSessionChangedRequest.client_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_pid', full_name='trackd.ClientSessionChangedRequest.server_pid', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_name', full_name='trackd.ClientSessionChangedRequest.session_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=308,
)


_CLIENTDETACHEDREQUEST = _descriptor.Descriptor(
  name='ClientDetachedRequest',
  full_name='trackd.ClientDetachedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='trackd.ClientDetachedRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_name', full_name='trackd.ClientDetachedRequest.client_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=372,
)


_SESSIONRENAMEDREQUEST = _descriptor.Descriptor(
  name='SessionRenamedRequest',
  full_name='trackd.SessionRenamedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='trackd.SessionRenamedRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_name', full_name='trackd.SessionRenamedRequest.client_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_pid', full_name='trackd.SessionRenamedRequest.server_pid', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_session_name', full_name='trackd.SessionRenamedRequest.new_session_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=482,
)


_SESSIONCLOSEDREQUEST = _descriptor.Descriptor(
  name='SessionClosedRequest',
  full_name='trackd.SessionClosedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='trackd.SessionClosedRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_pid', full_name='trackd.SessionClosedRequest.server_pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_name', full_name='trackd.SessionClosedRequest.session_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=566,
)

DESCRIPTOR.message_types_by_name['SetClientForXWindowIdRequest'] = _SETCLIENTFORXWINDOWIDREQUEST
DESCRIPTOR.message_types_by_name['ClearClientForXWindowIdRequest'] = _CLEARCLIENTFORXWINDOWIDREQUEST
DESCRIPTOR.message_types_by_name['ClientSessionChangedRequest'] = _CLIENTSESSIONCHANGEDREQUEST
DESCRIPTOR.message_types_by_name['ClientDetachedRequest'] = _CLIENTDETACHEDREQUEST
DESCRIPTOR.message_types_by_name['SessionRenamedRequest'] = _SESSIONRENAMEDREQUEST
DESCRIPTOR.message_types_by_name['SessionClosedRequest'] = _SESSIONCLOSEDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetClientForXWindowIdRequest = _reflection.GeneratedProtocolMessageType('SetClientForXWindowIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETCLIENTFORXWINDOWIDREQUEST,
  '__module__' : 'tmux_pb2'
  # @@protoc_insertion_point(class_scope:trackd.SetClientForXWindowIdRequest)
  })
_sym_db.RegisterMessage(SetClientForXWindowIdRequest)

ClearClientForXWindowIdRequest = _reflection.GeneratedProtocolMessageType('ClearClientForXWindowIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARCLIENTFORXWINDOWIDREQUEST,
  '__module__' : 'tmux_pb2'
  # @@protoc_insertion_point(class_scope:trackd.ClearClientForXWindowIdRequest)
  })
_sym_db.RegisterMessage(ClearClientForXWindowIdRequest)

ClientSessionChangedRequest = _reflection.GeneratedProtocolMessageType('ClientSessionChangedRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSESSIONCHANGEDREQUEST,
  '__module__' : 'tmux_pb2'
  # @@protoc_insertion_point(class_scope:trackd.ClientSessionChangedRequest)
  })
_sym_db.RegisterMessage(ClientSessionChangedRequest)

ClientDetachedRequest = _reflection.GeneratedProtocolMessageType('ClientDetachedRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTDETACHEDREQUEST,
  '__module__' : 'tmux_pb2'
  # @@protoc_insertion_point(class_scope:trackd.ClientDetachedRequest)
  })
_sym_db.RegisterMessage(ClientDetachedRequest)

SessionRenamedRequest = _reflection.GeneratedProtocolMessageType('SessionRenamedRequest', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONRENAMEDREQUEST,
  '__module__' : 'tmux_pb2'
  # @@protoc_insertion_point(class_scope:trackd.SessionRenamedRequest)
  })
_sym_db.RegisterMessage(SessionRenamedRequest)

SessionClosedRequest = _reflection.GeneratedProtocolMessageType('SessionClosedRequest', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONCLOSEDREQUEST,
  '__module__' : 'tmux_pb2'
  # @@protoc_insertion_point(class_scope:trackd.SessionClosedRequest)
  })
_sym_db.RegisterMessage(SessionClosedRequest)



_TMUX = _descriptor.ServiceDescriptor(
  name='Tmux',
  full_name='trackd.Tmux',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=569,
  serialized_end=1070,
  methods=[
  _descriptor.MethodDescriptor(
    name='set_client_for_x_window_id',
    full_name='trackd.Tmux.set_client_for_x_window_id',
    index=0,
    containing_service=None,
    input_type=_SETCLIENTFORXWINDOWIDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='clear_client_for_x_window_id',
    full_name='trackd.Tmux.clear_client_for_x_window_id',
    index=1,
    containing_service=None,
    input_type=_CLEARCLIENTFORXWINDOWIDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='client_session_changed',
    full_name='trackd.Tmux.client_session_changed',
    index=2,
    containing_service=None,
    input_type=_CLIENTSESSIONCHANGEDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='client_detached',
    full_name='trackd.Tmux.client_detached',
    index=3,
    containing_service=None,
    input_type=_CLIENTDETACHEDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='session_renamed',
    full_name='trackd.Tmux.session_renamed',
    index=4,
    containing_service=None,
    input_type=_SESSIONRENAMEDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='session_closed',
    full_name='trackd.Tmux.session_closed',
    index=5,
    containing_service=None,
    input_type=_SESSIONCLOSEDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TMUX)

DESCRIPTOR.services_by_name['Tmux'] = _TMUX

# @@protoc_insertion_point(module_scope)
